---
title: "Tidyverse Homework 3"
author: "Jessie Heise"
format: pdf
editor: visual
---

```{r}
# Load packages needed for assignment
library(tidyverse)
library(palmerpenguins)
```

```{r}
## Task 1
### Part a
#### We cannot use specifically the read.csv() to read in these data because
#### the delimiter is a semicolon instead of a comma. Instead we must use 
#### read.csv2()
# Read in data
read_csv2("Homework3data/data.txt", col_names = TRUE)
```

```{r}
### Part b
# Read in data2
read_delim("Homework3data/data2.txt", delim = "6", col_types = "fdc")
```

```{r}
## Task 2
### Part a
# Read in trailblazers data
trailblazer <- read_csv("Homework3data/trailblazer.csv")

# Make sure data read in correctly
glimpse(trailblazer)
```

```{r}
### Part b
# Pivot & tidy the data
trailblazer_longer <- 
  pivot_longer(
    trailblazer, 
    cols = starts_with("Game"), 
    names_to = "Game", 
    values_to = "Points"
    )
trailblazer_longer <- 
  separate(
    trailblazer_longer, 
    Game, 
    into = c("Game", "Location"), 
    sep = "_"
    )

head(trailblazer_longer, n = 5)
```

```{r}
### Part c
# Answer which players scored more, on average, when playing at home versus 
# away in a single pipline
trailblazer_wider <-
  pivot_wider(trailblazer_longer, 
              values_from = "Points", 
              names_from = "Location") %>%
  group_by(Player) %>%
  summarise(mean_home = mean(Home, na.rm = TRUE), 
         mean_away = mean(Away, na.rm = TRUE)) %>%
  mutate(mean_diff = mean_home - mean_away) %>%
  arrange(desc(mean_diff))
print(trailblazer_wider)

# Jusuf Nurkic, Robert Covington, Nassir Little, Damian Lillard, 
# and Cody Zeller scored, on average, more points at home through
# the first 10 games of the season than away.
```

```{r}
## Task 3
### Part a
#### <NULL> is saying that there are is no list for that species an island.
#### <dbl [52]> is describing that there is a vector of variables that are doubles.
#### <list> is describing that the output tibble contains a list.
### Part b
penguins %>%
  select(species, island, bill_length_mm) %>%
  count (species, island) %>%
  pivot_wider(values_from = n, names_from = island, values_fill = 0) %>%
  mutate(across(c(Biscoe, Dream, Torgersen), as.double))


```

```{r}
## Task 4
# Adelie is 26 and Gentoo is 30
penguins %>%
  mutate(
    bill_length_mm = ifelse(
      is.na(bill_length_mm),
      case_when(
        species == "Adelie" ~ 26,
        species == "Gentoo" ~ 30
        ),
      bill_length_mm
    )) %>%
  arrange(bill_length_mm) %>%
  head(penguins, n = 10)
```
